export enum OrgType {
  BUYER = 'BUYER',
  SUPPLIER = 'SUPPLIER',
  PLATFORM = 'PLATFORM',
}

export enum UserRole {
  BUYER_ADMIN = 'BUYER_ADMIN',
  SUPPLIER_ADMIN = 'SUPPLIER_ADMIN',
  PLATFORM_ADMIN = 'PLATFORM_ADMIN',
}

export enum TxnState {
  DRAFT = 'DRAFT',
  POLICY_CREATED = 'POLICY_CREATED',
  SUPPLIER_SELECTED = 'SUPPLIER_SELECTED',
  AWAITING_CREDENTIAL = 'AWAITING_CREDENTIAL',
  PROOF_GENERATING = 'PROOF_GENERATING',
  VERIFYING = 'VERIFYING',
  AUTHORIZED = 'AUTHORIZED',
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
  SETTLED = 'SETTLED',
  PROOF_INVALID = 'PROOF_INVALID',
  CREDENTIAL_EXPIRED = 'CREDENTIAL_EXPIRED',
  IDENTITY_MISMATCH = 'IDENTITY_MISMATCH',
  POLICY_FAILED = 'POLICY_FAILED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_TIMEOUT = 'PAYMENT_TIMEOUT',
  DISPUTED = 'DISPUTED',
  CANCELLED = 'CANCELLED',
}

export enum TransitionCause {
  AGENT_REQUEST = 'agent_request',
  ZK_VERIFIER = 'zk_verifier',
  WEBHOOK = 'webhook',
  SYSTEM_TIMEOUT = 'system_timeout',
  HUMAN_ACTION = 'human_action',
}

export enum PaymentStatus {
  CREATED = 'created',
  AUTHORIZED = 'authorized',
  CAPTURED = 'captured',
  FAILED = 'failed',
  REFUNDED = 'refunded',
}

export enum ActorType {
  AGENT = 'agent',
  SYSTEM = 'system',
  HUMAN = 'human',
  WEBHOOK = 'webhook',
}

export enum TrustLevel {
  SYNTHETIC_DEMO = 'SYNTHETIC_DEMO',
  PRODUCTION = 'PRODUCTION',
}

export enum IdempotencyAction {
  CREATE_ORDER = 'create_order',
  CAPTURE = 'capture',
  TRANSFER = 'transfer',
}

export enum VerificationVerdict {
  PASS = 'PASS',
  FAIL = 'FAIL',
}

export enum FailureCode {
  SIGNATURE_INVALID = 'SIGNATURE_INVALID',
  POLICY_HASH_MISMATCH = 'POLICY_HASH_MISMATCH',
  NONCE_MISMATCH = 'NONCE_MISMATCH',
  NONCE_ALREADY_CONSUMED = 'NONCE_ALREADY_CONSUMED',
  IDENTITY_MISMATCH = 'IDENTITY_MISMATCH',
  CREDENTIAL_EXPIRED = 'CREDENTIAL_EXPIRED',
  CREDENTIAL_REVOKED = 'CREDENTIAL_REVOKED',
  GROTH16_VERIFY_FAILED = 'GROTH16_VERIFY_FAILED',
  PROOF_REQUEST_EXPIRED = 'PROOF_REQUEST_EXPIRED',
  THRESHOLD_NOT_MET = 'THRESHOLD_NOT_MET',
}
